apiVersion: v2
name: seerr
description: A Helm chart for Seerr using lib-chart
type: application
version: 0.0.1
appVersion: "v3.1.0"
keywords:
  - seerr
  - media-center
  - requests
dependencies:
  - name: lib-chart
    version: "0.0.13"
    repository: "oci://ghcr.io/orhayoun-eevee"
maintainers:
  - name: Seerr Team
home: https://github.com/seerr-team/seerr
